apiVersion: v1
kind: Namespace
metadata:
  name: sample-app-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: pool-ips  # MetallbのIPプール名
      protocol: layer2
      addresses:
      - 192.168.192.250-192.168.192.254
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service-lb # Service(LoadBalancer) の名前
  namespace: sample-app-prod
  annotations:
    metallb.universe.tf/address-pool: pool-ips # MetallbのIPプール名
spec:
  type: LoadBalancer
  ports:
    - name: sample-app-service-lb
      protocol: TCP
      port: 8080 # ServiceのIPでlistenするポート
      nodePort: 30080 # nodeのIPでlistenするポート（30000-32767）
      targetPort: 8080 # 転送先(コンテナ)でlistenしているPort番号のポート
  selector: # service のselctorは、matchLabels 扱いになる
    app: sample-app-pod # 転送先の Pod のラベル
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment # Deployment の名前(ReplicaSetの名前もこれになる)
  namespace: sample-app-prod
spec:
  selector:
    matchLabels: # ラベルがマッチしたPodを対象とするReplicaSetの作成
      app: sample-app-pod
  replicas: 2
  template: # Pod のテンプレート
    metadata:
      name: sample-app-pod # Pod の名前
      namespace: sample-app-prod
      labels: # Pod のラベル
        app: sample-app-pod
    spec:
      containers: # コンテナの設定
        - name: sample-app-container # コンテナの名前
          image: "javasampleapp:0.0.1" # イメージの名前
          imagePullPolicy: Never
          env:
            - name: sample-app-container
          ports:
            - containerPort: 8080 # コンテナのポート

